# Generated by Django 3.2.6 on 2021-09-13 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210909_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='book_author',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='book_rating',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='book_title',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.DeleteModel(
            name='AdditionalImage',
        ),
    ]
